/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.vista;

/**
 *
 * @author OMAR MONTES
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JScrollPane();
        menu = new javax.swing.JMenuBar();
        menu_estructuras = new javax.swing.JMenu();
        menuListaS = new javax.swing.JMenuItem();
        menuListaD = new javax.swing.JMenuItem();
        menuListaC = new javax.swing.JMenuItem();
        menuListaCD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 550));

        menu_estructuras.setText("Estructuras");

        menuListaS.setText("Lista Simple");
        menuListaS.setActionCommand("lista-simple");
        menuListaS.setBorder(null);
        menu_estructuras.add(menuListaS);

        menuListaD.setText("Lista Doble");
        menuListaD.setActionCommand("lista-doble");
        menu_estructuras.add(menuListaD);

        menuListaC.setText("Lista Circular");
        menuListaC.setActionCommand("lista-circular");
        menu_estructuras.add(menuListaC);

        menuListaCD.setText("Lista Circular Doble");
        menuListaCD.setActionCommand("lista-circular_doble");
        menu_estructuras.add(menuListaCD);

        menu.add(menu_estructuras);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane contenedor;
    public javax.swing.JMenuBar menu;
    public javax.swing.JMenuItem menuListaC;
    public javax.swing.JMenuItem menuListaCD;
    public javax.swing.JMenuItem menuListaD;
    public javax.swing.JMenuItem menuListaS;
    public javax.swing.JMenu menu_estructuras;
    // End of variables declaration//GEN-END:variables
}
